// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxfbwjkorhmdheflcxgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4ZmJ3amtvcmhtZGhlZmxjeGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDUyNjEsImV4cCI6MjA2NjI4MTI2MX0.92HyV4LKGZ6_qXdo8a9PkXMEhln8Q2pPPUiSoH5UBq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);